## Importing:

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt #graphing
import matplotlib.patches as mpatches #style
import seaborn as sns #advanced graphing
import scipy as sp #math stuff
%matplotlib inline

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/house-prices-advanced-regression-techniques/test.csv


In [2]:
#importing csvs
train = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/train.csv')
test = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/test.csv')
train['train_test'] = 1
test['train_test'] = 0
all_data = pd.concat([train,test])

## Discovering:

In [3]:
#getting a general idea of variable types
all_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 82 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             2919 non-null   int64  
 1   MSSubClass     2919 non-null   int64  
 2   MSZoning       2915 non-null   object 
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64  
 5   Street         2919 non-null   object 
 6   Alley          198 non-null    object 
 7   LotShape       2919 non-null   object 
 8   LandContour    2919 non-null   object 
 9   Utilities      2917 non-null   object 
 10  LotConfig      2919 non-null   object 
 11  LandSlope      2919 non-null   object 
 12  Neighborhood   2919 non-null   object 
 13  Condition1     2919 non-null   object 
 14  Condition2     2919 non-null   object 
 15  BldgType       2919 non-null   object 
 16  HouseStyle     2919 non-null   object 
 17  OverallQual    2919 non-null   int64  
 18  OverallC

In [4]:
#getting an idea of the quantitative variables
all_data.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  2919.000000  2919.000000  2433.000000    2919.000000  2919.000000   
mean   1460.000000    57.137718    69.305795   10168.114080     6.089072   
std     842.787043    42.517628    23.344905    7886.996359     1.409947   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     730.500000    20.000000    59.000000    7478.000000     5.000000   
50%    1460.000000    50.000000    68.000000    9453.000000     6.000000   
75%    2189.500000    70.000000    80.000000   11570.000000     7.000000   
max    2919.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  2919.000000  2919.000000   2919.000000  2896.000000  2918.000000  ...   
mean      5.564577  1971.312778   1984.264474   102.201312   441.423235  ...   
std       1.113131    30.291442     20.894344   179.334253   455.610826  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1953.500000   1965.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1993.000000     0.000000   368.500000  ...   
75%       6.000000  2001.000000   2004.000000   164.000000   733.000000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

       OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch     PoolArea  \
count  2919.000000    2919.000000  2919.000000  2919.000000  2919.000000   
mean     47.486811      23.098321     2.602261    16.062350     2.251799   
std      67.575493      64.244246    25.188169    56.184365    35.663946   
min       0.000000       0.000000     0.000000     0.000000     0.000000   
25%       0.000000       0.000000     0.000000     0.000000     0.000000   
50%      26.000000       0.000000     0.000000     0.000000     0.000000   
75%      70.000000       0.000000     0.000000     0.000000     0.000000   
max     742.000000    1012.000000   508.000000   576.000000   800.000000   

            MiscVal       MoSold       YrSold      SalePrice   train_test  
count   2919.000000  2919.000000  2919.000000    1460.000000  2919.000000  
mean      50.825968     6.213087  2007.792737  180921.195890     0.500171  
std      567.402211     2.714762     1.314964   79442.502883     0.500086  
min        0.000000     1.000000  2006.000000   34900.000000     0.000000  
25%        0.000000     4.000000  2007.000000  129975.000000     0.000000  
50%        0.000000     6.000000  2008.000000  163000.000000     1.000000  
75%        0.000000     8.000000  2009.000000  214000.000000     1.000000  
max    17000.000000    12.000000  2010.000000  755000.000000     1.000000  

[8 rows x 39 columns]

In [5]:
#seperating variables in to quantitative and qualitative
qual_vars = []
quant_vars = []
for column in all_data.columns:
    if all_data[column].dtype == 'object':
        qual_vars.append(column)
    else:
        quant_vars.append(column)
quant_vars.remove('SalePrice')
quant_vars.remove('Id')
quant_vars.remove('MSSubClass')
qual_vars.append('MSSubClass')

In [6]:
all_data.isna().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       486
LotArea             0
                 ... 
YrSold              0
SaleType            1
SaleCondition       0
SalePrice        1459
train_test          0
Length: 82, dtype: int64

In [7]:
#replacing missing values
LotFrontageMedian = np.median(train['LotFrontage'].dropna())
GarageYrBltMedian = np.median(train['GarageYrBlt'].dropna())
MasVnrAreaMedian = np.median(train['MasVnrArea'].dropna())
BsmtFinSF1Median = np.median(train['BsmtFinSF1'].dropna())
BsmtFinSF2Median = np.median(train['BsmtFinSF2'].dropna())
BsmtUnfSFMedian = np.median(train['BsmtUnfSF'].dropna())
TotalBsmtSFMedian = np.median(train['TotalBsmtSF'].dropna())
BsmtFullBathMedian = np.median(train['BsmtFullBath'].dropna())
BsmtHalfBathMedian = np.median(train['BsmtHalfBath'].dropna())
GarageCarsMedian = np.median(train['GarageCars'].dropna())
GarageAreaMedian = np.median(train['GarageArea'].dropna())
values = {'LotFrontage': LotFrontageMedian, 'GarageYrBlt': GarageYrBltMedian, 'MasVnrArea': MasVnrAreaMedian
         ,'BsmtFinSF1': BsmtFinSF1Median, 'BsmtFinSF2': BsmtFinSF2Median, 'BsmtUnfSF': BsmtUnfSFMedian,
          'TotalBsmtSF': TotalBsmtSFMedian,'BsmtFullBath': BsmtFullBathMedian, 'BsmtHalfBath': BsmtHalfBathMedian,
          'GarageCars': GarageCarsMedian,'GarageArea': GarageAreaMedian}
test.fillna(value=values,inplace=True)
train.fillna(value=values, inplace=True)

In [8]:
#getting dummies
qual_vars.append('Id')
qual_vars.append('train_test')
dummies = pd.get_dummies(all_data[qual_vars])
train_dummies = dummies[dummies['train_test']==1]
test_dummies = dummies[dummies['train_test']==0]

In [9]:
#final split into x, y, test, and train
quant_vars.append('Id')
X_train = train[quant_vars]
X_train = X_train.merge(train_dummies, on='Id')
y_train = train['SalePrice']
X_test = test[quant_vars]
X_test = X_test.merge(test_dummies, on='Id')

## Exploratory Analysis:

In [10]:
#looking at correlations between qualitative variables and price graphically
#for var in quant_vars:
    #sns.regplot(data=train,x=var,y='SalePrice')
    #plt.show()

In [11]:
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

In [12]:
#looking at correlations between qualitative variables and price using r_squared
# for var in quant_vars:
#     x = X_train[var]
#     X = x[:, None]
#     reg = LinearRegression()
#     reg.fit(X,y_train)
#     y = reg.predict(X_test[var][:, None])
#     r2_score(y)

In [13]:
# X_test.isna().sum()

## Preliminary Correlations

In [14]:
#importing models
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from xgboost import XGBRegressor

In [15]:
#scaling
#scaler=StandardScaler()
#X_train_scaled = scaler.fit_transform(X_train)
#X_test_scaled = scaler.fit_transform(X_test)

In [16]:
#linear regression
reg = LinearRegression()
cv = cross_val_score(reg,X_train,y_train,cv=5)
print(cv)
print(np.mean(cv))

[0.82274251 0.82014796 0.7938363  0.88785855 0.64310393]
0.7935378524251281


In [17]:
#ridge regression
ridge = Ridge()
cv = cross_val_score(ridge,X_train,y_train)
print(cv)
print(np.mean(cv))

[0.88687651 0.82509237 0.86910092 0.87616255 0.68095448]
0.8276373640196087


In [18]:
#lasso regression
lasso = Lasso()
cv = cross_val_score(lasso,X_train,y_train)
print(cv)
print(np.mean(cv))

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.398e+11, tolerance: 7.592e+08
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.067e+11, tolerance: 7.288e+08
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisa

[0.85947633 0.81885361 0.81373485 0.88872842 0.64532243]
0.805223127996918


/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.923e+11, tolerance: 7.249e+08
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive


In [19]:
#XGBRegressor
xgb = XGBRegressor()
cv = cross_val_score(xgb,X_train,y_train)
print(cv)
print(np.mean(cv))

[0.85653569 0.82074884 0.85277911 0.89656454 0.87659978]
0.8606455910255774


**To do:**

Make dummies

Do more feature engineering

## Training Final Model

In [20]:
xgb_final = XGBRegressor()
xgb_final.fit(X_train,y_train)
y_test = xgb_final.predict(X_test)

In [21]:
final_data = {'Id': X_test['Id'], 'SalePrice': y_test}
submission = pd.DataFrame(data=final_data)
submission.to_csv('submission_xgb1.csv', index=False)